### ISSUE TITLE
Binding resolution exception

### ISSUE THREAD

**Issue by kitsao** [AjmerSingh7537/E-commerce_Project#1]
@AjmerSingh7537 , I've been trying to learn more by example using your project due to its simplicity, thumbs up! I get this error though,   

```
   BindingResolutionException in Container.php line 872:
  Unresolvable dependency resolving [Parameter #0 [ <required> $session ]] in class    Gloudemans\Shoppingcart\Cart
```

Apparently, it was raised [here](https://github.com/Crinsane/LaravelShoppingcart/issues/66) but it doesn't seem to work. Did you face the same issue? How did you go about it?

**Comment by AjmerSingh7537** [comment]
Thanks for using my project as an example. I really appreciate it. For the following problem:
<code>BindingResolutionException in Container.php line 872:
  Unresolvable dependency resolving [Parameter #0 [ <required> $session ]] in class    Gloudemans\Shoppingcart\Cart </code>

Can you please go to Gloudemans\Shoppingcart\Cart file and check if you have a constructor in that file looking as follows:
public function __construct(\Illuminate\Session\SessionManager $session, Dispatcher $event)
	{
		$this->session = $session;
		$this->event = $event;
		$this->instance = 'main';
	}

If the constructor in that file doesn't look like it, then replace it with the above code.

I was having the same exception when I remove \Illuminate\Session\SessionManager from the constructor's parameter <code>$session</code>. So, make sure that you have it inside the constructor's parameter.

I hope this helps.

**Comment by kitsao** [comment]
Great! Solved.
